/**
 * install.js — stage the hook client and declare it in ~/.claude/settings.json.
 *
 * The client is copied *out* of the app rather than run from it. Inside a
 * packaged build the sources live in app.asar, which only Electron can read, and
 * the app's own path changes the moment someone drags it to /Applications. A
 * staged copy under the data directory is stable, readable by plain node, and
 * survives the app moving.
 *
 * Everything here is idempotent: it compares before it writes, so a launch that
 * changes nothing touches no file and produces no watcher noise.
 */
const fs = require('fs');
const path = require('path');

const { reconcile, removeManaged, desiredCommand, HOOK_EVENTS } = require('./config');
const { socketPathFor } = require('./socket-path');

const HOOK_BIN_NAME = 'switchboard-hook';

// Copied verbatim into the staging directory; paths are relative to it.
const STAGED_FILES = Object.freeze([
  ['bin/switchboard-hook.js', 'bin/switchboard-hook.js'],
  ['agent-hooks/protocol.js', 'agent-hooks/protocol.js'],
  ['agent-hooks/config.js', 'agent-hooks/config.js'],
  ['agent-hooks/socket-path.js', 'agent-hooks/socket-path.js'],
]);

const hooksDir = (dataDir) => path.join(dataDir, 'hooks');
const hookBin = (dataDir) => path.join(hooksDir(dataDir), HOOK_BIN_NAME);

/**
 * The shim Claude Code actually invokes. It prefers a real node — a few
 * milliseconds against Electron's startup, which matters inside a 400 ms
 * budget — and falls back to the app itself running as node.
 */
function shimSource({ scriptPath, electronPath }) {
  return `#!/bin/sh
# Generated by Switchboard. Do not edit — it is rewritten at every launch.
SCRIPT="${scriptPath}"
# A settings.json entry outlives the install it points at. If the staged client
# is gone, say nothing and get out of the agent's way.
if [ ! -f "$SCRIPT" ]; then
  exit 0
fi
if command -v node >/dev/null 2>&1; then
  exec node "$SCRIPT" "$@"
fi
ELECTRON="${electronPath}"
if [ -x "$ELECTRON" ]; then
  ELECTRON_RUN_AS_NODE=1 exec "$ELECTRON" "$SCRIPT" "$@"
fi
exit 0
`;
}

/** Write only when the content actually differs. @returns {boolean} changed */
function writeIfDifferent(file, content, mode) {
  try {
    if (fs.readFileSync(file, 'utf8') === content) return false;
  } catch {
    // Missing or unreadable — fall through and write it.
  }
  fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 });
  fs.writeFileSync(file, content, { mode });
  return true;
}

/**
 * Copy the client into <dataDir>/hooks and (re)generate the shim.
 * @returns {{bin: string, changed: boolean}}
 */
function stage({ dataDir, appDir, electronPath }) {
  const dir = hooksDir(dataDir);
  let changed = false;

  for (const [from, to] of STAGED_FILES) {
    const source = fs.readFileSync(path.join(appDir, from), 'utf8');
    if (writeIfDifferent(path.join(dir, to), source, 0o600)) changed = true;
  }

  const bin = hookBin(dataDir);
  const shim = shimSource({ scriptPath: path.join(dir, 'bin', 'switchboard-hook.js'), electronPath });
  if (writeIfDifferent(bin, shim, 0o700)) changed = true;
  try { fs.chmodSync(bin, 0o700); } catch {}

  return { bin, changed };
}

function readSettings(file) {
  try {
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8'));
    return parsed && typeof parsed === 'object' ? parsed : {};
  } catch {
    return {};
  }
}

/**
 * Verify — and repair — our entries in a Claude Code settings file.
 * The file belongs to the user: it is rewritten only when something drifted,
 * and never when another install already owns an entry.
 */
function reconcileSettings({ settingsPath, bin, pathExists = fs.existsSync }) {
  const current = readSettings(settingsPath);
  const result = reconcile(current, { bin, pathExists });
  if (result.changed) {
    fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
    fs.writeFileSync(settingsPath, `${JSON.stringify(result.settings, null, 2)}\n`, { mode: 0o600 });
  }
  return { repaired: result.changed, conflicts: result.conflicts };
}

/** Remove every entry we own — used when the user turns the feature off. */
function uninstallSettings({ settingsPath }) {
  const result = removeManaged(readSettings(settingsPath));
  if (result.changed) {
    fs.writeFileSync(settingsPath, `${JSON.stringify(result.settings, null, 2)}\n`, { mode: 0o600 });
  }
  return { removed: result.changed };
}

/** True when every managed event currently points at our staged binary. */
function isInstalled({ settingsPath, bin }) {
  const settings = readSettings(settingsPath);
  return Object.keys(HOOK_EVENTS).every((event) => {
    const commands = (settings.hooks?.[event] || []).flatMap((g) => g.hooks || []).map((h) => h.command);
    return commands.includes(desiredCommand(bin, event));
  });
}

module.exports = {
  HOOK_BIN_NAME, STAGED_FILES,
  hooksDir, hookBin, socketPathFor, shimSource,
  stage, reconcileSettings, uninstallSettings, isInstalled,
};
